server.port=8082
spring.cloud.gateway.server.webmvc.routes[2].id=auth-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://SAVINGS-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/auth/**
